services:
  server:
    container_name: server
    build:
      context: ./server-json
    ports:
      - 3001:3001/tcp
    profiles:
      - dev
      - main

  grafana:
    container_name: grafana
    image: ghcr.io/volkovlabs/app:latest
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,marcusolsson-json-datasource,volkovlabs-variable-panel, volkovlabs-image-panel
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-form-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dev

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./server-pg:/docker-entrypoint-initdb.d
    profiles:
      - dev
      - main

  server-pg:
    container_name: server-pg
    build:
      context: ./server-pg
    ports:
      - 3002:3001/tcp
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    profiles:
      - dev
      - main

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    environment:
      - GRAFANA_HOST=postgres
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - grafana
    profiles:
      - dev

  nginx-main:
    container_name: nginx-main
    build: ./nginx
    restart: always
    environment:
      - GRAFANA_HOST=postgres
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - grafana-main
    profiles:
      - main

  grafana-main:
    container_name: grafana-main
    image: grafana/grafana:main
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,marcusolsson-json-datasource,volkovlabs-variable-panel, volkovlabs-image-panel
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-form-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - main

  test:
    container_name: test-e2e
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://127.0.0.1:3000
    volumes:
      - ./test:/app/test
      - ./playwright-report:/app/playwright-report
    network_mode: host
    profiles:
      - e2e
