version: '3.4'

services:
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 3001:3001/tcp

  grafana:
    container_name: grafana
    image: ghcr.io/volkovlabs/app:latest
    ports:
      - 3000:3000/tcp
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,marcusolsson-json-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-form-panel
      - ./provisioning:/etc/grafana/provisioning
      # Uncomment to preserve Grafana configuration
      # - ./data:/var/lib/grafana

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./server-pg:/docker-entrypoint-initdb.d

  server-pg:
    container_name: server-pg
    build:
      context: ./server-pg
    ports:
      - 3002:3001/tcp
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    environment:
      - GRAFANA_HOST=host.docker.internal
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - grafana

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: api
    ports:
      - 3306:3306
    volumes:
      - ./server-mysql:/docker-entrypoint-initdb.d

  server-mysql:
    container_name: server-mysql
    build:
      context: ./server-mysql
    ports:
      - 3003:3001/tcp
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_DB: api
