version: '3.4'

services:
  server:
    container_name: server
    build:
      context: ./server-json
    ports:
      - 3001:3001/tcp

  grafana:
    container_name: grafana
    depends_on:
      - server
    image: ghcr.io/volkovlabs/app:latest
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,marcusolsson-json-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-form-panel
      - ./provisioning:/etc/grafana/provisioning
