version: '3.4'

services:
  server:
    container_name: server
    build:
      context: ./postgres
    ports:
      - 3001:3001/tcp

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000/tcp
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_USERS_DEFAULT_THEME=light
      - GF_DEFAULT_APP_MODE=development
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-form-panel
      - ./provisioning:/etc/grafana/provisioning
      # Uncomment to preserve Grafana configuration
      # - ./data:/var/lib/grafana

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
