CREATE TABLE FEEDBACKS (
    ID INT NOT NULL AUTO_INCREMENT,
    CREATED DATETIME NOT NULL,
    USERNAME VARCHAR(255),
    EMAIL VARCHAR(255),
    DESCRIPTION VARCHAR(1000),
    TYPE VARCHAR(255),
    PRIMARY KEY (ID)
);